---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero
  require_chef_omnibus: "12"
  data_bags_path: test/shared/data_bags

platforms:
  - name: centos-7.2
  - name: centos-6.6
    driver:
      box: parallels/centos-6.6

suites:
  - name: default
    run_list:
      - recipe[bacula_test::default]
    attributes:
