AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
  Exclude:
    - test/**/*
    - vendor/**/*

LineLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'
HashSyntax:
  Enabled: false

AlignParameters:
  Exclude:
    - '**/metadata.rb'

MethodLength:
  Enabled: false

AbcSize:
  Enabled: false

Documentation:
  Enabled: false
