name             'bacula-client'
maintainer       'Pavel Yudin'
maintainer_email 'pyudin@parallels.com'
license          'Apache 2.0'
description      'Installs/Configures bacula-client'
long_description 'Installs/Configures bacula-client'
version          '0.1.0'

depends 'apt'
depends 'build-essential'
